# Generated by Django 2.1.15 on 2020-09-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecretboxMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretbox', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hidden.SecretBox')),
            ],
            options={
                'db_table': 'hidden_secretbox_members',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='secretboxmembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hidden.User'),
        ),
        migrations.AddField(
            model_name='secretbox',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='hidden.User'),
        ),
        migrations.AddField(
            model_name='secretbox',
            name='members',
            field=models.ManyToManyField(through='hidden.SecretboxMembers', to='hidden.User'),
        ),
        migrations.AlterUniqueTogether(
            name='secretboxmembers',
            unique_together={('secretbox', 'user')},
        ),
    ]
