# Generated by Django 2.1.15 on 2020-09-28 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hidden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='hidden.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box', to='hidden.SecretBox'),
        ),
    ]
