# Generated by Django 2.1.15 on 2020-11-02 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hidden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='exception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exceptions', to='hidden.Member'),
        ),
    ]
