# Generated by Django 2.1.15 on 2020-10-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretbox',
            name='limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secretbox',
            name='limitValue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
