# Generated by Django 2.1.15 on 2020-09-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden', '0002_auto_20200930_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretboxmembers',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='secretbox',
            name='members',
            field=models.ManyToManyField(related_name='members', through='hidden.SecretboxMembers', to='hidden.User'),
        ),
    ]
