# Generated by Django 2.1.15 on 2020-09-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hidden', '0002_auto_20200928_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretbox',
            name='description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='hidden.SecretBox'),
        ),
    ]
