# Generated by Django 2.1.15 on 2020-10-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden', '0002_auto_20201014_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='wishes',
            field=models.CharField(blank=True, default='', max_length=800, null=True),
        ),
    ]
