# Generated by Django 2.1.15 on 2020-10-01 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hidden', '0003_auto_20201001_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretboxmembers',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='friends', to='hidden.User'),
        ),
        migrations.AlterField(
            model_name='secretboxmembers',
            name='secretbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='secretboxs', to='hidden.SecretBox'),
        ),
        migrations.AlterField(
            model_name='secretboxmembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='hidden.User'),
        ),
    ]
