# Generated by Django 2.1.15 on 2020-09-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden', '0003_auto_20200929_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='box',
        ),
        migrations.AddField(
            model_name='secretbox',
            name='members',
            field=models.ManyToManyField(to='hidden.Customer'),
        ),
    ]
