# Generated by Django 2.1.15 on 2020-09-30 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hidden', '0004_auto_20200930_0837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='User',
        ),
    ]
