# Generated by Django 2.1.15 on 2020-10-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hidden', '0005_remove_secretboxmembers_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friends', to='hidden.User')),
                ('santa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='santas', to='hidden.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='secretboxmembers',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='secretboxmembers',
            name='secretbox',
        ),
        migrations.RemoveField(
            model_name='secretboxmembers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='secretbox',
            name='members',
        ),
        migrations.DeleteModel(
            name='SecretboxMembers',
        ),
        migrations.AddField(
            model_name='membership',
            name='secretbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='secretboxs', to='hidden.SecretBox'),
        ),
    ]
