# Generated by Django 2.1.15 on 2020-10-01 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hidden', '0007_auto_20201001_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='hidden.User'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='santa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='santas', to='hidden.User'),
        ),
    ]
